name: empymod
channels:
  - conda-forge
  - defaults
dependencies:
  - empymod
  - ipykernel
  - ipympl
  - ipywidgets
  - jupyter
  - jupyterlab
  - jupyterlab_widgets
  - matplotlib
  - numpy
  - scipy
