name: empymod
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=22.1.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.0.3
  - cryptography=36.0.1
  - cycler=0.11.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - empymod=2.1.3
  - entrypoints=0.4
  - executing=0.8.2
  - flit-core=3.6.0
  - fonttools=4.29.1
  - freetype=2.10.4
  - icu=64.2
  - idna=3.3
  - importlib-metadata=4.11.1
  - importlib_resources=5.4.0
  - ipykernel=6.9.1
  - ipympl=0.8.8
  - ipython=8.0.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.1.2
  - jupyter_console=6.4.0
  - jupyter_core=4.9.2
  - jupyter_server=1.13.5
  - jupyterlab=3.2.9
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=1.0.2
  - kiwisolver=1.3.2
  - lcms2=2.12
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=12.0.0
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp-base=1.2.2
  - llvm-openmp=13.0.1
  - llvmlite=0.37.0
  - lz4-c=1.9.3
  - markupsafe=2.1.0
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - nbclassic=0.3.5
  - nbclient=0.5.11
  - nbconvert=6.4.2
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.4
  - notebook=6.4.8
  - numba=0.54.1
  - numpy=1.20.3
  - olefile=0.46
  - openssl=1.1.1l
  - packaging=21.3
  - pandoc=2.17.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.9.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=21.2.4
  - platformdirs=2.5.0
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.27
  - prompt_toolkit=3.0.27
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyqt=5.9.2
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.2.2
  - qtconsole-base=5.2.2
  - qtpy=2.0.1
  - readline=8.1.2
  - requests=2.27.1
  - scipy=1.8.0
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.37.2
  - stack_data=0.2.0
  - terminado=0.13.1
  - testpath=0.5.0
  - tk=8.6.11
  - tomli=2.0.1
  - tornado=6.1
  - traitlets=5.1.1
  - typed-ast=1.5.2
  - typing_extensions=4.1.1
  - tzdata=2021e
  - unicodedata2=14.0.0
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.2.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
